version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mainstack
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src

